name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install Node dependencies
        run: pnpm install

      - name: Build site
        run: pnpm run build

      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist

      - uses: actions/upload-artifact@v7
        with:
          name: articles
          path: articles

      - uses: actions/upload-artifact@v7
        with:
          name: users
          path: users

      - uses: actions/upload-artifact@v7
        with:
          name: publickey
          path: publickey.pem

      - uses: actions/github-script@v8
        env:
          SUCCESSOR_NAME: ${{ github.event_name == 'pull_request' && 'deploy-preview' || 'deploy' }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const sha = context.payload.pull_request?.head?.sha || context.sha;
            
            await github.rest.repos.createCommitStatus({
              owner, repo, sha,
              state: "pending",
              context: `deploy / ${process.env.SUCCESSOR_NAME}`,
            });
